language: node_js
node_js:
  - 8

install:
  - npm install

script:
  - echo "No tests required"

deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  script:
    - echo "//registry.npmjs.org/:_password=${NPM_PASSWORD}" > ~/.npmrc
    - echo "//registry.npmjs.org/:_authToken=${NPM_API_KEY}" >> ~/.npmrc
    - echo "//registry.npmjs.org/:username=${NPM_USERNAME}" >> ~/.npmrc
    - echo "//registry.npmjs.org/:email=${NPM_EMAIL}" >> ~/.npmrc
    - npm publish
  on:
    branch: release
    tags: false
#Notify Team on Slack
notifications:
  slack: hackerbaycompany:gm7nWJDLDtBRyF75VKLKOoMW